name: ASN请求
description: 请求添加新的AS编号图片
title: "[ASN请求] "
labels: ["ASN请求"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: 请确认以下事项
      options:
        - label: 这是一个个人项目，请求需要较长时间处理，请耐心等待
          required: false
  
  - type: input
    id: asn
    attributes:
      label: AS编号
      description: 请提供您想要添加的AS编号
      placeholder: 例如：AS64512
    validations:
      required: true
  
  - type: textarea
    id: reference
    attributes:
      label: LOGO/参考图
      description: 请提供与此AS相关的LOGO或参考图
      placeholder: 请在此处上传或提供LOGO/参考图片链接
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: 其他信息
      description: 请提供任何其他相关信息
      placeholder: 可选：提供任何其他您认为有助于处理此请求的信息，如AS的所有者、用途等
    validations:
      required: false 